language: ruby
rvm:
- 2.2.0
addons:
  postgresql: '9.3'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database eval360_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: aVM+enL8CROwo8nmBiZLBmYpqWcAPQIsfaq+bZE4UTDqW0CH99qqnb1vmyLU/Jp8qlY6hLZCXDmlDvhHnfFfDBKm+zvpPntxXVfeDeAjJWDQSVHk67VZwyUzepi/KybAfbUojqveiIe3hkw+2qZA5ASlzMTOf0z7Ss7y67pTc00=
  app: rockwood
  skip_cleanup: true
  on:
    repo: rockwoodleadership/eval360
  run:
    - "rake db:migrate"
